openapi: 3.1.0
info:
  description: The Faro API accepts payloads from the Faro SDKs.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Faro API
  version: 1.0.0
servers:
- description: Faro Collector API
  url: "/collect/{appKey}"
  variables:
    appKey:
      default: default
      description: The application key is provided by your endpoint provider.
paths:
  /collect/{appKey}:
    post:
      operationId: submitPayload
      parameters:
      - description: |
          The application key is provided by your endpoint provider.
        explode: false
        in: path
        name: appKey
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payload'
        description: Optional description in *Markdown*
        required: true
      responses:
        default:
          description: OK
        "202":
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
          description: Internal Server Error
      summary: Submit a Faro payload
components:
  schemas:
    Event:
      example:
        domain: domain
        name: name
        attributes:
          key: attributes
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        name:
          type: string
        domain:
          type: string
        attributes:
          additionalProperties:
            type: string
        timestamp:
          format: date-time
          type: string
      required:
      - domain
      - name
      - timestamp
    Log:
      example:
        trace:
          trace_id: trace_id
          span_id: span_id
        level: level
        context:
          key: context
        message: message
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        message:
          type: string
        level:
          type: string
        context:
          additionalProperties:
            type: string
        timestamp:
          format: date-time
          type: string
        trace:
          $ref: '#/components/schemas/Log_trace'
      required:
      - level
      - message
      - timestamp
    StackFrame:
      example:
        in_app: true
        filename: filename
        lineno: 6
        colno: 0
        function: function
      properties:
        colno:
          type: integer
        filename:
          type: string
        function:
          type: string
        in_app:
          type: boolean
        lineno:
          type: integer
    Exception:
      example:
        trace:
          trace_id: trace_id
          span_id: span_id
        stacktrace:
        - in_app: true
          filename: filename
          lineno: 6
          colno: 0
          function: function
        - in_app: true
          filename: filename
          lineno: 6
          colno: 0
          function: function
        context:
          key: context
        type: type
        value: value
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        type:
          type: string
        value:
          type: string
        stacktrace:
          items:
            $ref: '#/components/schemas/StackFrame'
          minItems: 0
          type: array
        timestamp:
          format: date-time
          type: string
        trace:
          $ref: '#/components/schemas/Exception_trace'
        context:
          additionalProperties:
            type: string
      required:
      - timestamp
      - type
      - value
    Measurement:
      example:
        trace:
          trace_id: trace_id
          span_id: span_id
        values:
          key: 0.8008281904610115
        context:
          key: context
        type: type
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        values:
          additionalProperties:
            type: number
        type:
          type: string
        timestamp:
          format: date-time
          type: string
        trace:
          $ref: '#/components/schemas/Exception_trace'
        context:
          additionalProperties:
            type: string
      required:
      - timestamp
      - type
      - values
    SpanEvent:
      properties:
        attributes:
          items:
            description: TODO default missing array inner type to string
            type: string
          type: array
        droppedAttributesCount:
          type: integer
        name:
          type: string
        timeUnixNano:
          type: string
      required:
      - name
    SdkMeta:
      example:
        name: name
        version: version
      properties:
        name:
          type: string
        version:
          type: string
      required:
      - name
      - version
    AppMeta:
      example:
        environment: environment
        release: release
        name: name
        version: version
      properties:
        name:
          type: string
        release:
          type: string
        version:
          type: string
        environment:
          type: string
      required:
      - environment
      - name
      - release
      - version
    UserMeta:
      example:
        attributes:
          key: attributes
        id: id
        email: email
        username: username
      properties:
        username:
          type: string
        id:
          type: string
        email:
          type: string
        attributes:
          additionalProperties:
            type: string
    SessionMeta:
      example:
        attributes:
          key: attributes
        id: id
      properties:
        id:
          type: string
        attributes:
          additionalProperties:
            type: string
    PageMeta:
      example:
        url: url
      properties:
        url:
          type: string
    BrowserMeta:
      example:
        os: os
        name: name
        mobile: true
        version: version
      properties:
        name:
          type: string
        version:
          type: string
        os:
          type: string
        mobile:
          type: boolean
    Payload:
      example:
        meta:
          app:
            environment: environment
            release: release
            name: name
            version: version
          view:
            name: name
          session:
            attributes:
              key: attributes
            id: id
          browser:
            os: os
            name: name
            mobile: true
            version: version
          sdk:
            name: name
            version: version
          page:
            url: url
          user:
            attributes:
              key: attributes
            id: id
            email: email
            username: username
        traces: "{}"
        logs:
        - trace:
            trace_id: trace_id
            span_id: span_id
          level: level
          context:
            key: context
          message: message
          timestamp: 2000-01-23T04:56:07.000+00:00
        - trace:
            trace_id: trace_id
            span_id: span_id
          level: level
          context:
            key: context
          message: message
          timestamp: 2000-01-23T04:56:07.000+00:00
        events:
        - domain: domain
          name: name
          attributes:
            key: attributes
          timestamp: 2000-01-23T04:56:07.000+00:00
        - domain: domain
          name: name
          attributes:
            key: attributes
          timestamp: 2000-01-23T04:56:07.000+00:00
        exceptions:
        - trace:
            trace_id: trace_id
            span_id: span_id
          stacktrace:
          - in_app: true
            filename: filename
            lineno: 6
            colno: 0
            function: function
          - in_app: true
            filename: filename
            lineno: 6
            colno: 0
            function: function
          context:
            key: context
          type: type
          value: value
          timestamp: 2000-01-23T04:56:07.000+00:00
        - trace:
            trace_id: trace_id
            span_id: span_id
          stacktrace:
          - in_app: true
            filename: filename
            lineno: 6
            colno: 0
            function: function
          - in_app: true
            filename: filename
            lineno: 6
            colno: 0
            function: function
          context:
            key: context
          type: type
          value: value
          timestamp: 2000-01-23T04:56:07.000+00:00
        measurements:
        - trace:
            trace_id: trace_id
            span_id: span_id
          values:
            key: 0.8008281904610115
          context:
            key: context
          type: type
          timestamp: 2000-01-23T04:56:07.000+00:00
        - trace:
            trace_id: trace_id
            span_id: span_id
          values:
            key: 0.8008281904610115
          context:
            key: context
          type: type
          timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        events:
          items:
            $ref: '#/components/schemas/Event'
          minItems: 0
          type: array
        logs:
          items:
            $ref: '#/components/schemas/Log'
          minItems: 0
          type: array
        exceptions:
          items:
            $ref: '#/components/schemas/Exception'
          minItems: 0
          type: array
        measurements:
          items:
            $ref: '#/components/schemas/Measurement'
          type: array
        meta:
          $ref: '#/components/schemas/Payload_meta'
        traces:
          format: Traces
          type: object
      required:
      - meta
    Log_trace:
      example:
        trace_id: trace_id
        span_id: span_id
      properties:
        trace_id:
          type: string
        span_id:
          type: string
      required:
      - span_id
      - trace_id
    Exception_trace:
      example:
        trace_id: trace_id
        span_id: span_id
      properties:
        trace_id:
          type: string
        span_id:
          type: string
    Payload_meta_view:
      example:
        name: name
      properties:
        name:
          type: string
    Payload_meta:
      example:
        app:
          environment: environment
          release: release
          name: name
          version: version
        view:
          name: name
        session:
          attributes:
            key: attributes
          id: id
        browser:
          os: os
          name: name
          mobile: true
          version: version
        sdk:
          name: name
          version: version
        page:
          url: url
        user:
          attributes:
            key: attributes
          id: id
          email: email
          username: username
      properties:
        sdk:
          $ref: '#/components/schemas/SdkMeta'
        app:
          $ref: '#/components/schemas/AppMeta'
        user:
          $ref: '#/components/schemas/UserMeta'
        session:
          $ref: '#/components/schemas/SessionMeta'
        page:
          $ref: '#/components/schemas/PageMeta'
        browser:
          $ref: '#/components/schemas/BrowserMeta'
        view:
          $ref: '#/components/schemas/Payload_meta_view'
