openapi: 3.0.0
info:
  description: The Faro API accepts payloads from the Faro SDKs.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Faro API
  version: 1.0.0
servers:
- description: Faro Collector API
  url: "/collect/{appKey}"
  variables:
    appKey:
      default: default
      description: The application key is provided by your endpoint provider.
paths:
  /collect/{appKey}:
    post:
      operationId: submitPayload
      parameters:
      - description: |
          The application key is provided by your endpoint provider.
        explode: false
        in: path
        name: appKey
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payload'
        description: Optional description in *Markdown*
        required: true
      responses:
        default:
          description: OK
        "202":
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
          description: Internal Server Error
      summary: Submit a Faro payload
components:
  schemas:
    MeasurementContext:
      additionalProperties:
        type: string
      type: object
      x-go-type-skip-optional-pointer: true
    Session:
      description: holds metadata about the browser session the event originates from.
      example:
        attributes:
          key: attributes
        id: id
      properties:
        id:
          type: string
          x-go-type-skip-optional-pointer: true
          x-go-name: ID
        attributes:
          additionalProperties:
            type: string
          type: object
          x-go-type-skip-optional-pointer: true
      type: object
      x-go-type-skip-optional-pointer: true
    Stacktrace:
      description: is a collection of Frames.
      example:
        frames:
        - filename: filename
          lineno: 6
          colno: 0
          function: function
          module: module
        - filename: filename
          lineno: 6
          colno: 0
          function: function
          module: module
      properties:
        frames:
          items:
            $ref: '#/components/schemas/Frame'
          minItems: 0
          type: array
          x-go-type-skip-optional-pointer: true
      type: object
    App:
      description: holds metadata about the application event originates from.
      example:
        environment: environment
        release: release
        bundleId: bundleId
        name: name
        namespace: namespace
        version: version
      properties:
        bundleId:
          type: string
          x-go-type-skip-optional-pointer: true
          x-go-name: BundleID
        environment:
          type: string
          x-go-type-skip-optional-pointer: true
        name:
          type: string
          x-go-type-skip-optional-pointer: true
        namespace:
          type: string
          x-go-type-skip-optional-pointer: true
        release:
          type: string
          x-go-type-skip-optional-pointer: true
        version:
          type: string
          x-go-type-skip-optional-pointer: true
      type: object
      x-go-type-skip-optional-pointer: true
    SDK:
      description: holds metadata about the app agent that produced the event.
      example:
        name: name
        version: version
        integrations:
        - name: name
          version: version
        - name: name
          version: version
      properties:
        name:
          type: string
          x-go-type-skip-optional-pointer: true
        version:
          type: string
          x-go-type-skip-optional-pointer: true
        integrations:
          items:
            $ref: '#/components/schemas/SDKIntegration'
          type: array
          x-go-type-skip-optional-pointer: true
      type: object
      x-go-type-skip-optional-pointer: true
      x-go-name: SDK
    TimeFormat:
      enum:
      - 2006-01-02T15:04:05.999Z
      type: string
      x-enum-varnames:
      - RFC3339Milli
    K6:
      description: holds metadata about whether or not the run happened in a K6 browser.
      example:
        isK6Browser: true
      properties:
        isK6Browser:
          type: boolean
          x-go-type-skip-optional-pointer: true
      type: object
      x-go-type-skip-optional-pointer: true
    Event:
      description: holds RUM event data.
      example:
        trace:
          trace_id: trace_id
          span_id: span_id
        domain: domain
        name: name
        attributes:
          key: attributes
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        attributes:
          additionalProperties:
            type: string
          type: object
          x-go-type-skip-optional-pointer: true
        domain:
          type: string
          x-go-type-skip-optional-pointer: true
        name:
          type: string
        timestamp:
          format: date-time
          type: string
          x-go-type-skip-optional-pointer: true
        trace:
          $ref: '#/components/schemas/TraceContext'
      required:
      - name
      type: object
    SpanEvent:
      properties:
        attributes:
          items:
            description: TODO default missing array inner type to string
            type: string
          type: array
        droppedAttributesCount:
          type: integer
        name:
          type: string
        timeUnixNano:
          type: string
      required:
      - name
      type: object
    Measurement:
      description: holds the data for user provided measurements.
      example:
        trace:
          trace_id: trace_id
          span_id: span_id
        values:
          key: 0.8008281904610115
        context:
          key: context
        type: type
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        context:
          additionalProperties:
            type: string
          type: object
          x-go-type-skip-optional-pointer: true
        timestamp:
          format: date-time
          type: string
          x-go-type-skip-optional-pointer: true
        trace:
          $ref: '#/components/schemas/TraceContext'
        type:
          type: string
          x-go-type-skip-optional-pointer: true
        values:
          additionalProperties:
            format: double
            type: number
          type: object
          x-go-type-skip-optional-pointer: true
      type: object
      x-go-type-skip-optional-pointer: true
    View:
      description: holds metadata about a view.
      example:
        name: name
      properties:
        name:
          type: string
          x-go-type-skip-optional-pointer: true
      type: object
      x-go-type-skip-optional-pointer: true
    Log:
      description: controls the data that come into a Log message.
      example:
        trace:
          trace_id: trace_id
          span_id: span_id
        level: trace
        context:
          key: context
        message: message
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        context:
          additionalProperties:
            type: string
          description: is a string to string map structure that represents the context
            of a log message.
          type: object
          x-go-type-skip-optional-pointer: true
        level:
          $ref: '#/components/schemas/LogLevel'
        message:
          type: string
          x-go-type-skip-optional-pointer: true
        timestamp:
          format: date-time
          type: string
        trace:
          $ref: '#/components/schemas/TraceContext'
      required:
      - timestamp
      type: object
    Kind:
      enum:
      - event
      - exception
      - log
      - measurement
      - unknown
      type: string
    Frame:
      description: represents a single stacktrace frame.
      example:
        filename: filename
        lineno: 6
        colno: 0
        function: function
        module: module
      properties:
        colno:
          type: integer
          x-go-type-skip-optional-pointer: true
        filename:
          type: string
          x-go-type-skip-optional-pointer: true
        function:
          type: string
          x-go-type-skip-optional-pointer: true
        lineno:
          type: integer
          x-go-type-skip-optional-pointer: true
        module:
          type: string
          x-go-type-skip-optional-pointer: true
      type: object
    ExceptionContext:
      additionalProperties:
        type: string
      type: object
      x-go-type-skip-optional-pointer: true
    LogLevel:
      description: log level enum for incoming app logs.
      enum:
      - trace
      - debug
      - info
      - warning
      - error
      type: string
      x-go-type-skip-optional-pointer: true
      x-go-name: LogLevel
    User:
      description: holds metadata about the user related to an app event.
      example:
        attributes:
          key: attributes
        id: id
        email: email
        username: username
      properties:
        username:
          type: string
          x-go-type-skip-optional-pointer: true
        id:
          type: string
          x-go-type-skip-optional-pointer: true
          x-go-name: ID
        email:
          type: string
          x-go-type-skip-optional-pointer: true
        attributes:
          additionalProperties:
            type: string
          type: object
          x-go-type-skip-optional-pointer: true
      type: object
      x-go-type-skip-optional-pointer: true
    TraceContext:
      description: "holds trace id and span id associated to an entity (log, exception,\
        \ measurement...)."
      example:
        trace_id: trace_id
        span_id: span_id
      properties:
        span_id:
          type: string
          x-go-name: SpanID
          x-go-type-skip-optional-pointer: true
          x-omitempty: false
        trace_id:
          type: string
          x-go-name: TraceID
          x-go-type-skip-optional-pointer: true
          x-omitempty: false
      required:
      - span_id
      - trace_id
      type: object
      x-go-type-skip-optional-pointer: true
    Page:
      description: holds metadata about the web page event originates from.
      example:
        attributes:
          key: attributes
        id: id
        url: url
      properties:
        attributes:
          additionalProperties:
            type: string
          type: object
          x-go-type-skip-optional-pointer: true
        id:
          type: string
          x-go-type-skip-optional-pointer: true
          x-go-name: ID
        url:
          type: string
          x-go-type-skip-optional-pointer: true
          x-go-name: URL
      type: object
      x-go-type-skip-optional-pointer: true
    Browser:
      description: holds metadata about a client's browser.
      example:
        os: os
        name: name
        mobile: true
        version: version
      properties:
        name:
          type: string
          x-go-type-skip-optional-pointer: true
        version:
          type: string
          x-go-type-skip-optional-pointer: true
        os:
          type: string
          x-go-type-skip-optional-pointer: true
        mobile:
          type: boolean
          x-go-type-skip-optional-pointer: true
      type: object
      x-go-type-skip-optional-pointer: true
    SDKIntegration:
      description: holds metadata about a plugin/integration on the app agent that
        collected and sent the event.
      example:
        name: name
        version: version
      properties:
        name:
          type: string
          x-go-type-skip-optional-pointer: true
        version:
          type: string
          x-go-type-skip-optional-pointer: true
      type: object
    Meta:
      description: holds metadata about an app event.
      example:
        app:
          environment: environment
          release: release
          bundleId: bundleId
          name: name
          namespace: namespace
          version: version
        view:
          name: name
        session:
          attributes:
            key: attributes
          id: id
        browser:
          os: os
          name: name
          mobile: true
          version: version
        sdk:
          name: name
          version: version
          integrations:
          - name: name
            version: version
          - name: name
            version: version
        page:
          attributes:
            key: attributes
          id: id
          url: url
        k6:
          isK6Browser: true
        user:
          attributes:
            key: attributes
          id: id
          email: email
          username: username
      properties:
        sdk:
          $ref: '#/components/schemas/SDK'
        app:
          $ref: '#/components/schemas/App'
        user:
          $ref: '#/components/schemas/User'
        session:
          $ref: '#/components/schemas/Session'
        page:
          $ref: '#/components/schemas/Page'
        browser:
          $ref: '#/components/schemas/Browser'
        k6:
          $ref: '#/components/schemas/K6'
        view:
          $ref: '#/components/schemas/View'
      type: object
      x-go-type-skip-optional-pointer: true
    Exception:
      description: holds all the data regarding an exception.
      example:
        trace:
          trace_id: trace_id
          span_id: span_id
        stacktrace:
          frames:
          - filename: filename
            lineno: 6
            colno: 0
            function: function
            module: module
          - filename: filename
            lineno: 6
            colno: 0
            function: function
            module: module
        context:
          key: context
        type: type
        value: value
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        context:
          additionalProperties:
            type: string
          type: object
          x-go-type-skip-optional-pointer: true
        stacktrace:
          $ref: '#/components/schemas/Stacktrace'
        timestamp:
          format: date-time
          type: string
        trace:
          $ref: '#/components/schemas/TraceContext'
        type:
          type: string
          x-go-type-skip-optional-pointer: true
        value:
          type: string
          x-go-type-skip-optional-pointer: true
      required:
      - timestamp
      type: object
    LogContext:
      additionalProperties:
        type: string
      description: is a string to string map structure that represents the context
        of a log message.
      type: object
      x-go-type-skip-optional-pointer: true
    Payload:
      description: is the body of the receiver request.
      example:
        meta:
          app:
            environment: environment
            release: release
            bundleId: bundleId
            name: name
            namespace: namespace
            version: version
          view:
            name: name
          session:
            attributes:
              key: attributes
            id: id
          browser:
            os: os
            name: name
            mobile: true
            version: version
          sdk:
            name: name
            version: version
            integrations:
            - name: name
              version: version
            - name: name
              version: version
          page:
            attributes:
              key: attributes
            id: id
            url: url
          k6:
            isK6Browser: true
          user:
            attributes:
              key: attributes
            id: id
            email: email
            username: username
        traces: ""
        logs:
        - trace:
            trace_id: trace_id
            span_id: span_id
          level: trace
          context:
            key: context
          message: message
          timestamp: 2000-01-23T04:56:07.000+00:00
        - trace:
            trace_id: trace_id
            span_id: span_id
          level: trace
          context:
            key: context
          message: message
          timestamp: 2000-01-23T04:56:07.000+00:00
        events:
        - trace:
            trace_id: trace_id
            span_id: span_id
          domain: domain
          name: name
          attributes:
            key: attributes
          timestamp: 2000-01-23T04:56:07.000+00:00
        - trace:
            trace_id: trace_id
            span_id: span_id
          domain: domain
          name: name
          attributes:
            key: attributes
          timestamp: 2000-01-23T04:56:07.000+00:00
        exceptions:
        - trace:
            trace_id: trace_id
            span_id: span_id
          stacktrace:
            frames:
            - filename: filename
              lineno: 6
              colno: 0
              function: function
              module: module
            - filename: filename
              lineno: 6
              colno: 0
              function: function
              module: module
          context:
            key: context
          type: type
          value: value
          timestamp: 2000-01-23T04:56:07.000+00:00
        - trace:
            trace_id: trace_id
            span_id: span_id
          stacktrace:
            frames:
            - filename: filename
              lineno: 6
              colno: 0
              function: function
              module: module
            - filename: filename
              lineno: 6
              colno: 0
              function: function
              module: module
          context:
            key: context
          type: type
          value: value
          timestamp: 2000-01-23T04:56:07.000+00:00
        measurements:
        - trace:
            trace_id: trace_id
            span_id: span_id
          values:
            key: 0.8008281904610115
          context:
            key: context
          type: type
          timestamp: 2000-01-23T04:56:07.000+00:00
        - trace:
            trace_id: trace_id
            span_id: span_id
          values:
            key: 0.8008281904610115
          context:
            key: context
          type: type
          timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        events:
          items:
            $ref: '#/components/schemas/Event'
          minItems: 0
          type: array
          x-go-type-skip-optional-pointer: true
        exceptions:
          items:
            $ref: '#/components/schemas/Exception'
          minItems: 0
          type: array
          x-go-type-skip-optional-pointer: true
        logs:
          items:
            $ref: '#/components/schemas/Log'
          minItems: 0
          type: array
          x-go-type-skip-optional-pointer: true
        measurements:
          items:
            $ref: '#/components/schemas/Measurement'
          type: array
          x-go-type-skip-optional-pointer: true
        meta:
          $ref: '#/components/schemas/Meta'
        traces:
          description: otel traces model.
          x-go-type: ptrace.Traces
          x-go-type-import:
            name: ptrace
            path: go.opentelemetry.io/collector/pdata/ptrace
      type: object
    Traces:
      description: otel traces model.
      x-go-type: ptrace.Traces
      x-go-type-import:
        name: ptrace
        path: go.opentelemetry.io/collector/pdata/ptrace
